import { Router } from "express";
import authRoutes from "./authRoutes.js";
import campaignRoutes from "./campaignRoutes.js";
import influencerRoutes from "./influencerRoutes.js";
import applicationRoutes from "./applicationRoutes.js";
import contractRoutes from "./contractRoutes.js";
import reviewRoutes from "./reviewRoutes.js";
import brandRoutes from "./brandRoutes.js";
import adminRoutes from "./adminRoutes.js";
import invitationRoutes from "./invitationRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import deliverableRoutes from "./deliverableRoutes.js";
import paymentRoutes from "./paymentRoutes.js";
import conversationRoutes from "./conversationRoutes.js";

const router = Router();
router.use("/auth", authRoutes);
router.use("/campaigns", campaignRoutes);
router.use("/influencers", influencerRoutes);
router.use("/applications", applicationRoutes);
router.use("/contracts", contractRoutes);
router.use("/reviews", reviewRoutes);
router.use("/brands", brandRoutes);
router.use("/admin", adminRoutes);
router.use("/invitations", invitationRoutes);
router.use("/notifications", notificationRoutes);
router.use("/deliverables", deliverableRoutes);
router.use("/payments", paymentRoutes);
router.use("/conversations", conversationRoutes);
export default router;
